[workspace]
resolver = "2"
members = ["crates/*"]

[patch.crates-io]
bevy_egui = { git = "https://github.com/ramirezmike/bevy_egui?rev=906b693b7a13266849af94c2280a54adad4333a3", branch = "bevy-0.14" }
