[workspace]
resolver = "2"
members = ["crates/*"]

[patch.crates-io]
bevy_egui = { git = "https://github.com/ramirezmike/bevy_egui?rev=0a7d2bdf686f9f10570cecf61733118ddd736d52", branch = "bevy-0.14" }
